academy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),

	url(r'', include('home.urls')),
    url(r'^accounts/', include('accounts.urls')),
	url(r'^api/accounts/', include('accounts.api.urls')),
	url(r'^api/videos/', include('videos.api.urls')),
	url(r'^videos/', include('videos.urls')),
]

accounts/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from rest_framework_jwt.views import obtain_jwt_token

from .views import UserCreateAPIView

app_name = 'accounts-api'
urlpatterns = [
  # url(r'^register/$', UserCreateAPIView.as_view(), name='register'),
  # url(r'^login/$', obtain_jwt_token, name='login')
]

accounts/urls.py
from importlib import import_module
from django.conf.urls import include, url
from allauth.socialaccount import providers
from .views import RegisterView, LoginView
from django.contrib.auth.views import LogoutView

urlpatterns = [
  url(r'^social/', include('allauth.socialaccount.urls')),
  url(r'^register/', RegisterView.as_view(), name='register'),
  url(r'^login/', LoginView.as_view(), name='login'),
  url(r'^logout/', LogoutView.as_view(), name='logout')
]

for provider in providers.registry.get_list():
  try:
    prov_mod = import_module(provider.get_package() + '.urls')
  except ImportError:
    continue
  prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
  if prov_urlpatterns:
    urlpatterns += prov_urlpatterns

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index')
]

videos/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
  VideoListAPIView,
  VideoDetailAPIView,
  # VideoDestroyAPIView,
  # VideoUpdateAPIView,
  )

urlpatterns = [
  url(r'^$', VideoListAPIView.as_view(), name='list'),
  url(r'^(?P<pk>\d+)/$', VideoDetailAPIView.as_view(), name='detail'),
  # url(r'^(?P<pk>\d+)/destroy/$', VideoDestroyAPIView.as_view(), name='destroy'),
  # url(r'^(?P<pk>\d+)/edit/$', VideoUpdateAPIView.as_view(), name='update'),
]

#### SLUG IMPLEMENTATION: https://www.youtube.com/watch?v=dWZB_F32BDg&list=PLEsfXFp6DpzTOcOVdZF-th7BS_GYGguAS&index=6

videos/urls.py
from django.conf.urls import url

from . import views

app_name = 'videos'
urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<course>[\w-]+)/$', views.ListView.as_view(), name='list')
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

videos/models.py
from django.db import models
from django.utils import timezone

class Course(models.Model):
  name = models.CharField(max_length=200)
  slug = models.CharField(max_length=200, unique=True)

  def __str__(self):
    return self.name

class Chapter(models.Model):
  course = models.ForeignKey(Course, on_delete=models.PROTECT)
  name = models.CharField(max_length=200)
  slug = models.CharField(max_length=200, unique=True)

  def __str__(self):
    return self.name

  def get_videos(self):
    return self.video_set.filter(chapter_id=self.id)

class Video(models.Model):
  chapter = models.ForeignKey(Chapter, on_delete=models.PROTECT)
  name = models.CharField(max_length=200)
  url = models.URLField()
  pub_date = models.DateTimeField('date published')

  def __str__(self):
    return self.name

  def get_vimeo_id(self):
    return self.url.rsplit('/', 1)[-1]

accounts/forms.py
from django.core.validators import validate_email
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegistrationForm(UserCreationForm):
  email = forms.EmailField(label='Email', required=True)

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

  def __init__(self, *args, **kwargs):
    super(RegistrationForm, self).__init__(*args, **kwargs)
    self.fields['username'].widget.attrs.pop("autofocus", None)
    self.fields['password1'].help_text = '''
      <b>Password Strength:</b><br>
      <span>
        Must contain 8 characters, both letters and numbers.
        Must not be similar to email or username.
        Must not be commonly used password.
      </span>
    '''

    self.fields['email'].help_text = '''
      We will use your email address for things like keeping
      your account secure, helping people find you, and
      sending notifications. You will always have control
      over this functionality through your Account Settings.
    '''

  def save(self, commit=True):
    user = super(RegistrationForm, self).save(commit=False)
    email = self.cleaned_data['email']
    if commit:
      user.save()
    return user


class LoginForm(AuthenticationForm):

  def __init__(self, *args, **kwargs):
    super(LoginForm, self).__init__(*args, **kwargs)
    self.fields['username'].widget.attrs.pop("autofocus", None)

accounts/api/views.py
from django.contrib.auth import get_user_model

from rest_framework.generics import CreateAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST, HTTP_201_CREATED
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.permissions import AllowAny
from rest_framework.authentication import SessionAuthentication, BasicAuthentication

from .serializers import (
  UserCreateSerializer,
  UserLoginSerializer
)

class UserCreateAPIView(CreateAPIView):
  permission_classes = [AllowAny]
  serializer_class = UserCreateSerializer

  def post(self, request, *args, **kwargs):
    serializer = UserCreateSerializer(data=request.data)
    if serializer.is_valid(raise_exception=True):
      serializer.save()
      return Response(serializer.data, status=HTTP_201_CREATED)
    return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

# class UserLoginAPIView(APIView):
#   permission_classes = [AllowAny]
#   serializer_class = UserLoginSerializer

#   def post(self, request, *args, **kwargs):
#     serializer = UserLoginSerializer(data=request.data)
#     if serializer.is_valid(raise_exception=True):
#       return Response(serializer.data, status=HTTP_200_OK)
#     return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth import login

from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect

from accounts.forms import RegistrationForm

# Create your views here.
class RegisterView(generic.CreateView):
  form_class = RegistrationForm
  model = User

  def post(self, request, *args, **kwargs):
    form = RegistrationForm(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponse(status=201)
    return HttpResponse(form.errors.as_json(), status=400)

class LoginView(auth_views.LoginView):
  def form_invalid(self, form):
    error_message = 'Username or Password invalid. Please try again'
    return HttpResponse(error_message, status=401)

  def form_valid(self, form):
    login(self.request, form.get_user())
    return HttpResponse(status=200)

home/views.py
from django.views import generic

class IndexView(generic.TemplateView):
	template_name = 'home/index.html'

videos/api/views.py
from rest_framework.generics import (
  # DestroyAPIView,
  ListAPIView,
  RetrieveAPIView,
  # UpdateAPIView,
)

from rest_framework.permissions import (
  AllowAny,
  IsAuthenticated,
  IsAdminUser,
  IsAuthenticatedOrReadOnly,
)

from videos.models import Video
from .serializers import VideoDetailSerializer, VideoListSerializer

# class VideoDestroyAPIView(DestroyAPIView):
#   queryset = Video.objects.all()
#   serializer_class = VideoDetailSerializer

class VideoDetailAPIView(RetrieveAPIView):
  queryset = Video.objects.all()
  serializer_class = VideoDetailSerializer
  permission_classes = [IsAuthenticated]

class VideoListAPIView(ListAPIView):
  queryset = Video.objects.all()
  serializer_class = VideoListSerializer
  permission_classes = [IsAuthenticated]

  #def get_queryset():

# class VideoUpdateAPIView(UpdateAPIView):
#   queryset = Video.objects.all()
#   serializer_class = VideoDetailSerializer

videos/views.py
from django.views import generic

from .models import Course, Chapter, Video

class IndexView(generic.ListView):
	template_name = 'videos/index.html'
	context_object_name = 'courses'

	def get_queryset(self):
		return Course.objects.all()

class ListView(generic.ListView):
	template_name = 'videos/list.html'
	context_object_name = 'chapters'

	def get_queryset(self):
		return Chapter.objects.filter(course__slug=self.kwargs['course'])

class DetailView(generic.DetailView):
	model = Video
	template_name = 'videos/detail.html'

home/templates/home/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block tab_content %}

<p>General home page content here.</p>

<a href="{% url 'videos:index' %}">Courses</a>

{% endblock %}

templates/base.html
{% load static %}
{% load compress %}
{% load widget_tweaks %}
{% load socialaccount %}
<script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'materialize/js/bin/materialize.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'accounts.js' %}"></script>

{% block static_files %}{% endblock %}

{% compress css %}
	<link rel="stylesheet" type="text/x-scss" href="{% static 'sass/base.scss' %}" />
	<link rel="stylesheet" type="text/x-scss" href="{% static 'materialize/sass/materialize.scss' %}" />
{% endcompress %}
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
	<nav class="nav-extended">
		<div class="nav-wrapper">
			<a href="/" class="brand-logo">
				TorqNoodle
			</a>
			<a href="#" data-activates="mobile-side-nav" class="button-collapse">
				<i class="material-icons">menu</i>
			</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				{% if request.user.is_authenticated %}
					<li>
						<a class="btn waves-effect waves-light" href="{% url 'logout' %}">
							Log Out
						</a>
					</li>
				{% else %}
					<li>
						<a class="btn waves-effect waves-light modal-trigger" href="#log_in_modal">
							Log In
						</a>
					</li>
					<li>
						<a class="btn waves-effect waves-light modal-trigger" href="#register_modal">
							Register
						</a>
					</li>
				{% endif %}
			</ul>
			<ul id="mobile-side-nav" class="side-nav">
				{% if request.user.is_authenticated %}
					<li>
						<div class="user-view">
							<div class="background">
							</div>
							<span class="white-text name">
								{{ request.user.username }}
							</span>
							<span class="white-text email">
								{{ request.user.email }}
							</span>
						</div>
					</li>
					<li>
						<a class="btn waves-effect waves-light" href="{% url 'logout' %}">
							Log Out
						</a>
					</li>
				{% else %}
					<li>
						<a class="btn waves-effect waves-light modal-trigger" href="#log_in_modal">
							Log In
						</a>
					</li>
					<li>
						<a class="btn waves-effect waves-light modal-trigger" href="#register_modal">
							Register
						</a>
					</li>
				{% endif %}
			</ul>
		</div>
		<div class="nav-content">
			{% block tabs %}{% endblock %}
		</div>
	</nav>
</header>
<div class="container">
	{% block tab_content %}{% endblock %}

	<!-- Register Modal -->
	<div id="register_modal" class="modal">
		<div class="modal-content">
			<div class="modal-header">
				<a class="btn-floating btn waves-effect waves-light modal-close">
					<i class="material-icons">arrow_back</i>
				</a>
				<h4 >Register</h4>
			</div>
			{% get_providers as socialaccount_providers %}
			<ul class="socialaccount_providers">
				{% include "socialaccount/snippets/provider_list.html" with process="login" %}
			</ul>
			<h5>- Or -</h5>
			<form class="register" id="register_form" data-url="{% url 'register' %}">
				{% csrf_token %}
				{% for field in register_form %}
					<div class="row field-row">
						<div class="input-field col s12">
							{% render_field field class+='tooltipped validate' data-tooltip=field.help_text %}
							<label for="{{ field.id_for_label }}" data-error="">
								{{ field.label }}
							</label>
						</div>
					</div>
				{% endfor %}
				<button type="submit" class="waves-effect waves-light btn">Register</button>
			</form>
		</div>
	</div>

	<!-- Log In Modal -->
	<div id="log_in_modal" class="modal">
		<div class="modal-content">
			<div class="modal-header">
				<a class="btn-floating btn waves-effect waves-light modal-close">
					<i class="material-icons">arrow_back</i>
				</a>
				<h4 >Log In</h4>
			</div>
			{% get_providers as socialaccount_providers %}
			<ul class="socialaccount_providers">
				{% include "socialaccount/snippets/provider_list.html" with process="login" %}
			</ul>
			<h5>- Or -</h5>
			<form class="login" id="login_form" method="POST" action="{% url 'login' %}">
				{% csrf_token %}
				{% for field in login_form %}
					<div class="row field-row">
						<div class="input-field col s12">
							{% render_field field class+='validate' %}
							<label for="{{ field.id_for_label }}" data-error="">
								{{ field.label }}
							</label>
						</div>
					</div>
				{% endfor %}
				<label id="login_form_error" class="form_error"></label>
				<button type="submit" class="waves-effect waves-light btn">Login</button>
			</form>
		</div>
	</div>
</div>
</body>
</html>

videos/templates/videos/index.html
{% extends "base.html" %}

{% block title %}Courses{% endblock %}

{% block tab_content %}

{% if courses %}
<ul>
  {% for course in courses %}
  <li>
    <a href="{% url 'videos:list' course=course.slug %}">{{ course.name }}</a>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No Courses Available.</p>
{% endif %}

{% endblock %}

videos/templates/videos/list.html
{% extends "base.html" %}

{% load static %}

{% block static_files %}
<script src="https://player.vimeo.com/api/player.js"></script>
<script src="{% static 'videos.js' %}"></script>
{% endblock %}

{% block title %}Chapters/Videos/Quizzes{% endblock %}

{% block tabs %}
<ul class="tabs tabs-transparent">
  <li class="tab"><a href="#videos">Watch</a></li>
  <li class="tab"><a href="#articles">Read</a></li>
  <li class="tab"><a href="#questions">Ask</a></li>
</ul>
{% endblock %}

{% block tab_content %}

<div id="videos" class="col s12">
  {% if chapters %}
  <ul>
    {% for chapter in chapters %}
      <li>
        <div class="col s12">
          <h4 class="header">{{ chapter.name }}</h4>
          {% if chapter.get_videos %}
            {% for video in chapter.get_videos %}
              <div class="card horizontal modal-trigger video-card" id="{{ video.get_vimeo_id }}" href="#video_modal_{{ video.id }}">
                <div class="card-image">
                  <img>
                </div>
                <div class="card-stacked">
                  <div class="card-content">
                    <span class="card-title">{{ vid.info.title }}</span>
                    <p>{{ vid.info.description }}</p>
                  </div>
                </div>
              </div>
              <div id="video_modal_{{ video.id }}" class="modal">
                <div class="modal-content" data-vimeo-url="{{ video.url }}">
                </div>
              </div>
            {% endfor %}
          {% else %}
            <p>No videos for this chapter</p>
          {% endif %}
        </div>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No Chapters Available.</p>
  {% endif %}
</div>

<div id="articles" class="col s12">
  <p>Articles</p>
</div>

<div id="questions" class="col s12">
  <p>Questions</p>
</div>

{% endblock %}